boatrace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('daily_result.urls')), 
    path('accounts/', include('allauth.urls')), 
]

daily_result/urls.py
from django.urls import path

from . import views


app_name = 'daily_result'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('daily-result-form/', views.DailyResultFormView.as_view(), name="daily_result_form"), 
    path('daily-result', views.DailyResultView.as_view(), name="daily_result"), 
    path('prob-form', views.ProbFormView.as_view(), name="prob_form"), 
    path('prob', views.ProbView.as_view(), name="prob"), 
    path('race-result-select/', views.RaceResultSelectView.as_view(), name="race_result_select"), 
    path('race-result/<str:race_date>/<str:place_id>/<str:race_no>/', views.RaceResultView.as_view(), name="race_result"), 
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"), 
    path('current-situation', views.CurrentSituationView.as_view(), name="current_situation"), 
]

daily_result/models.py
from django.db import models

daily_result/forms.py
from django.core.mail import EmailMessage
from django import forms


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=50)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=50)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def send_email(self):
        """メール送信処理"""

        # ユーザー入力値の取得
        # self.cleaned_data['<フィールド名>'] とすることで、フォームバリデーションを通ったユーザー入力値を取得できる.
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        # メール送信情報
        subject = f'お問い合わせ {title}'
        message = (
            '送信者: {}\n'.format(name) + 
            'メールアドレス: {}\n'.format(email) + 
            'メッセージ:\n{}'.format(message)
        )
        from_email = 'yamashi7227.04020105.7227@outlook.jp'
        to_list = ['yamashi7227.04020105.7227@outlook.jp']
        cc_list = [email]

        # メール送信（EmailMessageオブジェクトのインスタンス化 -> 送信）
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

daily_result/views.py
import logging
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from datetime import datetime
from django.conf import settings
from django.http import JsonResponse
from pprint import pprint

from . import models
from .forms import InquiryForm
from .lib import DealBucketData

logger = logging.getLogger(__name__)


DICT_PLACE = {
    '01': '桐生', 
    '02': '戸田', 
    '03': '江戸川', 
    '04': '平和島', 
    '05': '多摩川', 
    '06': '浜名湖', 
    '07': '蒲郡', 
    '08': '常滑', 
    '09': '津', 
    '10': '三国', 
    '11': 'びわこ', 
    '12': '住之江', 
    '13': '尼崎', 
    '14': '鳴門', 
    '15': '丸亀', 
    '16': '児島', 
    '17': '宮島', 
    '18': '徳山', 
    '19': '下関', 
    '20': '若松', 
    '21': '芦屋', 
    '22': '福岡', 
    '23': '唐津', 
    '24': '大村'
}


class IndexView(generic.TemplateView):
    template_name = "index.html"

class DailyResultFormView(generic.TemplateView):
    """ GCSから一日の収支結果を取得し表示するためのフォーム """

    template_name = "form.html"

    def post(self, request):
        # Get posted data.
        post_data = {
            'year': request.POST['year'], 
            'month': request.POST['month'], 
            'day': request.POST['day'], 
        }

        # GCSからデータ取得
        bucket_dealer = DealBucketData('boat_race_ai', 'boat_race_ai')
        context = bucket_dealer.get_daily_betting_result(post_data)
        context['dividend_ratio_each_comb'] = bucket_dealer.get_dividend_ratio_each_comb(post_data)

        pprint(context)

        # エラーがなければ結果を表示、エラー（該当ファイルがないなど）があればエラーページを表示
        if context.get('error') == None:
            return render(request, 'result.html', context)
        else:
            return render(request, 'error_page.html', context)

class DailyResultView(generic.TemplateView):
    """ フォーム情報を受け取り、表示する """
    template_name = "result.html"

class ProbFormView(generic.TemplateView):
    """ 「１レースの各買い目に対する予測確率」を表示するための入力フォーム """

    template_name = "prob_form.html"

    def post(self, request):
        post_data = {
            'year': request.POST['year'], 
            'month': request.POST['month'], 
            'day': request.POST['day'], 
            'place_id': request.POST['place_id'], 
            'race_no': request.POST['race_no'], 
        }

        # GCSからデータ取得
        bucket_dealer = DealBucketData('boat_race_ai', 'boat_race_ai')
        context = bucket_dealer.get_prob(post_data)

        return render(request, 'prob.html', context)

class ProbView(generic.TemplateView):
    """ 確率出力 """
    template_name = "prob.html"

class RaceResultSelectView(generic.TemplateView):
    """ 見たいレース結果を選択するページ """

    template_name = "race_result_select.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # GCSからデータ取得
        bucket_dealer_boat = DealBucketData('boat_race_ai', 'boat_race_ai')
        bucket_dealer_keiba = DealBucketData('keiba-ai', 'keiba-ai')
        context["todays_race_count"] = bucket_dealer_keiba.read_todays_race_count()
        context["place_count"] = len(context["todays_race_count"])
        context["now_date"] = datetime.now().strftime('%Y%m%d')

        return context
    
class RaceResultView(generic.TemplateView):
    """ レース結果の詳細を表示 """

    template_name = "race_result.html"

    def get(self, request, **kwargs):

        # クエリパラメータ
        race_date = kwargs['race_date']
        place_id = kwargs['place_id']
        race_no = kwargs['race_no']

        # GCS（betting_results）からデータ取得
        bucket_dealer = DealBucketData('boat_race_ai', 'boat_race_ai')
        dct = bucket_dealer.get_betting_results(race_date, place_id, race_no)

        # contextに格納
        context = dct.copy()    # {trifecta: [{'first': '1', 'second': '2', ...}, {...}, ...]}}

        # レースが終了していない場合
        if context['is_finished'] == False:
            return render(request, 'not_finish_race.html', context)

        # レース結果のスクレイピング結果（実際のレース結果）
        context['race_result'] = bucket_dealer.get_race_result(race_date, place_id, race_no)    # {'trifecta': ['1-2-3'], 'triple': ['1-2-3'], 'exacta': ['1-2'], ...}

        # レース結果のアイコン表示用
        if len(context['race_result']['trifecta']) != 0:
            bracket_first = context['race_result']['trifecta']['comb'][0][0]
            bracket_second = context['race_result']['trifecta']['comb'][0][2]
            bracket_thrid = context['race_result']['trifecta']['comb'][0][4]

            context['bracketFirst'] = '{}.png'.format(bracket_first)
            context['bracketSecond'] = '{}.png'.format(bracket_second)
            context['bracketThird'] = '{}.png'.format(bracket_thrid)

        # レース情報
        context['place_name'] = DICT_PLACE[place_id]

        # 開発用
        context['race_date'] = race_date
        context['place_id'] = place_id
        context['race_no'] = race_no

        print('views')
        pprint(context)

        return self.render_to_response(context)

class InquiryView(generic.FormView):
    """お問合せ"""

    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('daily_result:inquiry')  # 正しく送信された時にリダイレクトされるとこ

    # フォームバリデーションに問題がなかったら実行されるメソッド（親クラスのメソッド）
    def form_valid(self, form):
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        form.send_email()
        messages.success(self.request, 'お問い合わせありがとうございました。')
        return super().form_valid(form)

class CurrentSituationView(generic.TemplateView):
    template_name = "current_situation.html"
    
    def get(self, request, **kwargs):
        # GCS（betting_results）からデータ取得
        bucket_dealer_boat = DealBucketData('boat_race_ai', 'boat_race_ai')
        context = {}
        context['balance'] = bucket_dealer_boat.get_current_balance()

        # GCS（keiba-ai: meta/todays_bettings_and_results.json）読み込み
        bucket_dealer_keiba = DealBucketData('keiba-ai', 'keiba-ai')
        context['bettings_and_results'] = bucket_dealer_keiba.get_todays_bettings_and_results()

        # テンプレート側でフィルターをかけるためのリストを定義
        context['race_no_list'] = [str(_) for _ in range(1, 13)]
        context['result_contents'] = ['buy_sum', 'return_sum', 'benefit']

        pprint(context)

        return render(request, 'current_situation.html', context)

daily_result/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
        
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/race_result_select.css' %}">

        <!-- pyscript -->
        <!-- <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
        <script defer src="https://pyscript.net/alpha/pyscript.js"></script> -->
        {% block head %}{% endblock head %}
    </head>
    <body>
        <!-- ヘッダー -->
        <nav class="nav-main">
            <div class="container-header">
                <ul class="ul-header">
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:daily_result_form' %}">１日の成績</a></li>
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:prob_form' %}">確率</a></li>
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:race_result_select' %}">予測結果</a></li>
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:current_situation' %}">速報</a></li>
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:inquiry' %}">お問い合わせ</a></li>

                    {% if user.is_authenticated %}
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'account_logout' %}">ログアウト</a></li>
                    {% else %}
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link {% block active_signup %}{% endblock active_signup %}" href="{% url 'account_signup' %}">サインアップ</a></li>
                    <li class="header-inner-li"><a class="text-white decorate-none nav-link {% block active_login %}{% endblock active_login %}" href="{% url 'account_login' %}">ログイン</a></li>
                    {% endif %}

                    <li class="header-inner-li"><a class="text-white decorate-none nav-link" href="{% url 'daily_result:index' %}">TOP</a></li>
                </ul>

                <span class="nav-toggle">
                    <i></i>
                    <i></i>
                    <i></i>
                </span>

                <div class="nav-humburger">
                    <ul class="nav-menu-ul list-style-none">
                        <li class="nav-menu-li"><a href="{% url 'daily_result:index' %}">TOP</a></li>
                        <li class="nav-menu-li"><a href="{% url 'daily_result:daily_result_form' %}">１日の成績</a></li>
                        <li class="nav-menu-li"><a href="{% url 'daily_result:prob_form' %}">確率</a></li>
                        <li class="nav-menu-li"><a href="{% url 'daily_result:race_result_select' %}">予測結果</a></li>
                        <li class="nav-menu-li"><a href="{% url 'daily_result:current_situation' %}">速報</a></li>
                        <li class="nav-menu-li"><a href="{% url 'daily_result:inquiry' %}">お問い合わせ</a></li>

                        {% if user.is_authenticated %}
                        <li class="nav-menu-li"><a href="{% url 'account_logout' %}">ログアウト</a></li>
                        {% else %}
                        <li class="nav-menu-li"><a href="{% url 'account_signup' %}">サインアップ</a></li>
                        <li class="nav-menu-li"><a href="{% url 'account_login' %}">ログイン</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- ローディング時のアニメーション画面 -->

        <section id="loading-display">

        </section>

        {% block header %}{% endblock header %}

        {% block contents %}{% endblock contents %}

        <!-- フッター -->
        <!-- <footer>
            <div class="container-footer">
                <p class="text-white block center-v text-footer">thanks</p>
            </div>
        </footer> -->

        <!-- js読み込み -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="{% static 'js/anime.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/form_common.js' %}"></script>
    </body>
</html>

daily_result/templates/error_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Daily Result{% endblock title %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'css/error_page.css' %}">
{% endblock head %}

{% block contents %}

<section>
    <div class="wrapper-header align-center">
        <h1 class="inline-center main-header align-center">エラー</h1>
        <p>全てのレースが終了するまでお待ちください。</p>
    </div>
</section>

{% endblock contents %}

daily_result/templates/form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Daily Result{% endblock title %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'css/form_common.css' %}">
{% endblock head %}

{% block contents %}

<section class="section-form">
    <h1 class="inline-center main-header">Daily Result</h1>
    <div class="align-center">
        <p>
            調べたい日付を選択してください。
        </p>
    </div>
    <form action="#" method="post" class="wrapper-form">
        {% csrf_token %}
        <div class="form-content">
            <div class="wrapper-form-label disp-flex-row">
                <img src="{% static 'assets/calendar.png' %}">
                <div>
                    <h3>date</h3>
                </div>
            </div>
            <div class="wrapper-form-raceDate">
                <select name="year" id="id_year" class="select"></select>
                <select name="month" id="id_month" class="select"></select>
                <select name="day" id="id_day" class="select"></select>
            </div>
        </div>
        <button>SEARCH</button>
    </form>
</section>

{% endblock contents %}

daily_result/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}お湯ラボ{% endblock title %}

{% block contents %}
<div class="container-contents-outer">
    <div class="container-contents-inner align-center" id="container-top-img">
        <h1 class="topPage-header">OYU LAB.</h1>
        <div class="wrapper-first-view disp-flex-row">
            <img src="{% static 'assets/main.png' %}">
            <img id="second-first-view" src="{% static 'assets/main.png' %}">
        </div>
    </div>
</div>

<!-- about -->

<section class="about">
    <div class="wrapper-header align-center">
        <h2 class="header">About</h2>
        <p>本サイトについて</p>
    </div>
    <div class="about-explain">
        <p>
            こちらでは、競艇の機械学習モデル「oyukiwa」の予測結果をご覧いただけます。<br>
            不具合・バグ等については温かい目で見守っていただけると幸いです。
        </p>
    </div>
</section>

<!-- what is boatrace -->

<section class="whatIsBoatrace">
    <div class="wrapper-header align-center">
        <h2 class="header">What is Boatrace</h2>
        <p>ボートレースとは？</p>
    </div>
    <div class="boatrace-explain align-center">
        <p>
            競艇とは、プロの選手がモーターボートに乗って着順を競い合うレースであり、公営ギャンブルの一つです。
        </p>
        <p>
            さらに、公営競技の中で最も当てやすいと言われているのが「競艇」です。
        </p>
        <p>
            なぜなら、競艇は１レース6艇のみで行われるため、他の公営競技に比べ組み合わせが少ないからです。
        </p>
    </div>
    <div class="wrapper-boatrace-content disp-flex-row">
        <div class="boatrace-content">
            <div class="boatrace-content-header disp-flex-row">
                <img src="{% static 'assets/racer.png' %}">
                <p>競技人数</p>
            </div>
            <div class="boatrace-content-header-val align-center">
                <p><span>6</span>人</p>
            </div>
        </div>
        <div class="boatrace-content">
            <div class="boatrace-content-header disp-flex-row">
                <img src="{% static 'assets/distance.png' %}">
                <p>距離</p>
            </div>
            <div class="boatrace-content-header-val align-center">
                <p><span>1800</span>m</p>
            </div>
        </div>
        <div class="boatrace-content">
            <div class="boatrace-content-header disp-flex-row">
                <img src="{% static 'assets/speedometer.png' %}">
                <p>最高速度</p>
            </div>
            <div class="boatrace-content-header-val align-center">
                <p><span>70</span>km/h</p>
            </div>
        </div>
        <div class="boatrace-content">
            <div class="boatrace-content-header disp-flex-row">
                <img src="{% static 'assets/arena.png' %}">
                <p>会場数</p>
            </div>
            <div class="boatrace-content-header-val align-center">
                <p><span>24</span>会場</p>
            </div>
        </div>
    </div>
</section>

<!-- service -->

<section class="service font-arial">
    <div class="wrapper-aboutHeader align-center">
        <h2 class="header">Service</h2>
        <p>できること</p>
    </div>
    <div class="card-container">
        <div class="card">
            <div class="face face1">
                <div class="card-content align-center">
                    <img src="{% static 'assets/results.png' %}">
                    <h3>１日の成績</h3>
                </div>
            </div>
            <div class="face face2">
                <div class="card-content">
                    <p>
                        予測に基づいた買い目による、１日の収支結果を確認できます。
                    </p>
                    <a href="{% url 'daily_result:daily_result_form' %}">移動する</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="face face1">
                <div class="card-content align-center">
                    <img src="{% static 'assets/probability.png' %}">
                    <h3>確率</h3>
                </div>
            </div>
            <div class="face face2">
                <div class="card-content">
                    <p>
                        １レースごとの、各買い目に対するモデルの的中確率を確認できます。
                    </p>
                    <a href="{% url 'daily_result:prob_form' %}">移動する</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="face face1">
                <div class="card-content align-center">
                    <img src="{% static 'assets/tickets.png' %}">
                    <h3>予測結果</h3>
                </div>
            </div>
            <div class="face face2">
                <div class="card-content">
                    <p>
                        １レースごとの、モデルの算出した期待値に基づく買い目や、実際のレース結果を確認できます。
                    </p>
                    <a href="{% url 'daily_result:race_result_select' %}">移動する</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="face face1">
                <div class="card-content align-center">
                    <img src="{% static 'assets/timeline.png' %}">
                    <h3>速報</h3>
                </div>
            </div>
            <div class="face face2">
                <div class="card-content">
                    <p>
                        当日の収支グラフやレース結果など、様々な情報を確認できます。
                    </p>
                    <a href="{% url 'daily_result:current_situation' %}">移動する</a>
                </div>
            </div>
        </div>
    </div>

    <!-- レスポンシブ時のservice -->

    <div class="card-container-responsive align-center">
        <div class="card-responsive">
            <div class="wrapper-card-header disp-flex-col">
                <div>
                    <div>
                        <h2>Daily Result</h2>
                    </div>
                    <div>
                        <p>１日の成績</p>
                    </div>
                </div>
            </div>
            <div class="wrapper-card-content">
                <img src="{% static 'assets/results.png' %}">
                <p>
                    予測に基づいた買い目による、１日の収支結果を確認できます。
                </p>
                <div class="card-line"></div>
                <div class="wrapper-go-detail-button">
                    <div>
                        <h2><a href="{% url 'daily_result:daily_result_form' %}">移動する</a></h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-responsive">
            <div class="wrapper-card-header disp-flex-col">
                <div>
                    <div>
                        <h2>Probability</h2>
                    </div>
                    <div>
                        <p>確率</p>
                    </div>
                </div>
            </div>
            <div class="wrapper-card-content">
                <img src="{% static 'assets/probability.png' %}">
                <p>
                    １レースごとの、各買い目に対するモデルの的中確率を確認できます。
                </p>
                <div class="card-line"></div>
                <div class="wrapper-go-detail-button">
                    <div>
                        <h2><a href="{% url 'daily_result:prob_form' %}">移動する</a></h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-responsive">
            <div class="wrapper-card-header disp-flex-col">
                <div>
                    <div>
                        <h2>Prediction</h2>
                    </div>
                    <div>
                        <p>予測結果</p>
                    </div>
                </div>
            </div>
            <div class="wrapper-card-content">
                <img src="{% static 'assets/tickets.png' %}">
                <p>
                    １レースごとの、モデルの算出した期待値に基づく買い目や、実際のレース結果を確認できます。
                </p>
                <div class="card-line"></div>
                <div class="wrapper-go-detail-button">
                    <div>
                        <h2><a href="{% url 'daily_result:race_result_select' %}">移動する</a></h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-responsive">
            <div class="wrapper-card-header disp-flex-col">
                <div>
                    <div>
                        <h2>Timeline</h2>
                    </div>
                    <div>
                        <p>速報</p>
                    </div>
                </div>
            </div>
            <div class="wrapper-card-content">
                <img src="{% static 'assets/timeline.png' %}">
                <p>
                    当日の収支グラフやレース結果など、様々な情報を確認できます。
                </p>
                <div class="card-line"></div>
                <div class="wrapper-go-detail-button">
                    <div>
                        <h2><a href="{% url 'daily_result:current_situation' %}">移動する</a></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock contents %}

daily_result/templates/inquiry.html
{% extends 'base.html' %}

{% load static %}

{% block title %}お問い合わせ{% endblock title %}

{% block head %}<link type="text/css" rel="stylesheet" href="{% static 'css/inquiry.css' %}">{% endblock head %}

{% block contents %}

    <section id="inquiry">
        <div class="wrapper-header align-center">
            <h1 class="inline-center main-header align-center">お問い合わせ</h1>
            <p>
                ご質問等ございましたらお問い合わせフォームにて受け付けております。<br>
                必要事項をご記入の上「送信」ボタンよりお問い合わせください。
            </p>
        </div>

        <!-- メッセージがある場合 -->

        {% if messages %}
            <div class="wrapper-message align-center">
                {% for message in messages %}
                <h3>{{ message }}</h3>
                {% endfor %}
            </div>
        {% endif %}

        <div class="wrapper-form">
            <form id="inquiry-form" method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-content">
                        {{ field }}<span class="highlight"></span><span class="bar"></span>
                        {{ field.label_tag }}
                        {{ field.errors }}
                    </div>
                {% endfor %}

                <button type="submit">送信</button>
            </form>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static 'js/anime.min.js' %}"></script>
    <script src="{% static 'js/authentication.js' %}"></script>

{% endblock contents %}

daily_result/templates/not_finish_race.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Daily Result{% endblock title %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'css/error_page.css' %}">
{% endblock head %}

{% block contents %}

<section>
    <div class="wrapper-header align-center">
        <h1 class="inline-center main-header align-center">エラー</h1>
        <p>対象のレースがまだ終了していません。</p>
        <div class="wrapper-link">
            <a class="link-err" href="{% url 'daily_result:race_result_select' %}">＜＜＜ レース一覧へ戻る</a>
        </div>
    </div>
</section>

{% endblock contents %}

daily_result/templates/race_result_select.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Daily Result{% endblock title %}

{% block head %}<link type="text/css" rel="stylesheet" href="{% static 'css/race_result_select.css' %}">{% endblock head %}

{% block contents %}
<div class="container-contents-outer text-align-center">
    <div class="container-contents-inner wrapper-title">
        <h1 class="main-text">本日のレース一覧</h1>
        <p>
            確認したいレースを選択してください。
        </p>
    </div>
    <main>
        {% if todays_race_count|length != 0 %}
        {% for race in todays_race_count %}
        <section class="wrapper-race-select">
            <div class="place"><div class="place-inner"><h4 class="header-2">{{ race.place_name }}</h4><div></div>
            <div class="wrapper-raceNo">
                <ul class="li-raceNo">
                    {% with ''|center:race.race_count as range %}
                    {% for _ in range %}
                    <li class="li-content">
                        <a class="raceNo" href="{% url 'daily_result:race_result' now_date race.place_id forloop.counter %}">{{ forloop.counter }}R</a>
                        <hr>
                        <p class="time">00:00</p>
                    </li>
                    {% endfor %}
                    {% endwith %}
                </ul>
            </div>
        </section>
        {% endfor %}
        {% else %}
        <div>
            <h2>読み込み失敗</h2>
        </div>
        {% endif %}
    </main>
</div>
{% endblock contents %}